site_name: Frontend Development Notes
site_description: Frontend Development Learning Notes and Documentation
site_author: Yalin(Eric) Yang
site_url: https://gisyaliny.github.io/Frontend/
copyright: Copyright &copy; 2024 - 2025 Yalin Yang

# Repository
repo_name: gisyaliny/Frontend
repo_url: https://github.com/gisyaliny/Frontend

# Configuration
theme:
    name: material
    language: en
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - navigation.top
        - navigation.footer
        - search.highlight
        - search.share
        - content.code.copy
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/gisyaliny/Frontend
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/gisyaliny/
    generator: false  # Disable "Made with Material for MkDocs" footer text

extra_css:
    - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.mark
  
plugins:
    - search
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago

nav:
    - Home: index.md
    - JavaScript:
        - Basics: "javascript/basics.md"
        - ES6+: "javascript/es6.md"
        - DOM Manipulation: "javascript/dom.md"
    - Frameworks:
        - React:
            - Introduction: "frameworks/react/intro.md"
            - Components: "frameworks/react/components.md"
            - Hooks: "frameworks/react/hooks.md"
        - Vue:
            - Introduction: "frameworks/vue/intro.md"
            - Components: "frameworks/vue/components.md"
    - CSS:
        - Basics: "css/basics.md"
        - Flexbox: "css/flexbox.md"
        - Grid: "css/grid.md"
    - Tools:
        - Webpack: "tools/webpack.md"
        - Babel: "tools/babel.md"
        - Git: "tools/git.md"